### ISSUE TITLE
MoE merging and "--clone-tensors flag is not set" warning.

### ISSUE THREAD

**Issue by PhilipMay** [arcee-ai/mergekit#279]
Hi. 
When I follow the MoE guide here: https://github.com/arcee-ai/mergekit/blob/main/docs/moe.md

I get this warning.

`WARNING:root:Your model has duplicated tensors but the --clone-tensors flag is not set.`

Could you please provide info on the doc page why this happens and when or if the `--clone-tensors` flag should be set?

Many thanks
Philip

**Comment by PhilipMay** [comment]
@cg123 can you please help me here? Many thanks. :-)

**Comment by cg123** [comment]
This is completely benign. This happens when a single tensor from a model is used in multiple places, like when doing sparse upcycling with the moe script or doing passthrough merges that repeat layers. Having `--clone-tensors` set can use slightly more memory, but having it unset will slow down saving and introduce small memory usage spikes in cases where this warning occurs. It's honestly a small enough difference that the warning could be removed entirely.

Hope this helps!

**Comment by PhilipMay** [comment]
Thanks. Closing this because of PR #296.
